### ISSUE TITLE
srfchwx - Can't see the extract url icon anymore

### ISSUE THREAD

**Issue by stzgr** [kaespi/srfchwx#1]
Dear kaespi

Not sure if it's a temporary problem, but at the moment, I can't see the icon anymore which is used to extract the links.

Cheers and kind regards

T.

**Comment by b3nno** [comment]
srf play hat einen neuen auftritt bekommen. somit funktioniert das add on nicht mehr...

**Comment by kaespi** [comment]
Sorry for being so ignorant to your requests/questions. In fact I wasn't aware about you posting here. Sorry! I finally found some time to fix it. The latest version (v2.0.3) should fix all the problems. You can get it from https://addons.mozilla.org/en-US/firefox/addon/srfch/. Please let me know about the specific page, in case you disagree.
